-- Baseline copied from tenant schema 767524024827354 on 2026-08-14.
-- The migration runner must replace {{schema}} with a validated numeric orgid.
-- This migration creates structure only; it does not copy tenant rows.

CREATE SCHEMA IF NOT EXISTS "{{schema}}";

CREATE SEQUENCE IF NOT EXISTS "{{schema}}".customers_number_seq
  START WITH 10000
  INCREMENT BY 1
  MINVALUE 10000
  NO MAXVALUE
  CACHE 1;

CREATE TABLE IF NOT EXISTS "{{schema}}".customers (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  number numeric DEFAULT nextval('"{{schema}}".customers_number_seq'::regclass),
  name text,
  phone numeric,
  CONSTRAINT customers_pkey PRIMARY KEY (id)
);

ALTER SEQUENCE "{{schema}}".customers_number_seq
  OWNED BY "{{schema}}".customers.number;

CREATE TABLE IF NOT EXISTS "{{schema}}".discount (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  weight double precision,
  CONSTRAINT discount_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "{{schema}}"."group" (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  number numeric,
  name text,
  data jsonb,
  CONSTRAINT group_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "{{schema}}".payment (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  customerid numeric,
  credit boolean,
  debit boolean,
  data jsonb,
  CONSTRAINT payment_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "{{schema}}".processingstatus (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  number numeric,
  description text,
  CONSTRAINT processingstatus_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "{{schema}}".purchase (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  date date,
  data jsonb,
  status bigint,
  sortingdata jsonb,
  number numeric,
  fromorg numeric,
  CONSTRAINT purchae_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "{{schema}}".sales (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  date date,
  data jsonb,
  summary jsonb,
  buydata jsonb,
  CONSTRAINT sales_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "{{schema}}".sorting (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  purchasedate date,
  purchasenumber numeric,
  number numeric,
  productid bigint,
  productdesc text,
  sizeid bigint,
  sizedesc text,
  quantity double precision,
  allocatedquantity double precision,
  allocationcomplete boolean,
  CONSTRAINT sorting_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "{{schema}}".buyerallocation (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  purchasedate date,
  product bigint,
  productdesc text,
  size bigint,
  sizedesc text,
  buyerphone numeric,
  buyername text,
  allocatedweight double precision,
  maxprice double precision,
  minprice double precision,
  buyerprice double precision,
  buyerquantity double precision,
  buyerweightdiscount double precision,
  sortingnumber numeric,
  buyerpurchase numeric,
  isbuyeronboarded boolean,
  CONSTRAINT buyerallocation_pkey PRIMARY KEY (id)
);
