CREATE TABLE IF NOT EXISTS "{{schema}}".supplier (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text,
  phone numeric,
  CONSTRAINT supplier_pkey PRIMARY KEY (id)
);
