CREATE TABLE IF NOT EXISTS "{{schema}}".interest_calculation (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  weight_limit numeric,
  interest_value double precision,
  weight_unit integer,
  CONSTRAINT interest_calculation_pkey PRIMARY KEY (id)
);
