'use strict';

const { schemaFromOrgid } = require('./customerRepository');

function createPurchaseRepository(pool) {
  return {
    async findDataForSorting(orgid) {
      const schema = schemaFromOrgid(orgid);
      const result = await pool.query(`
        SELECT "data", "number"
        FROM ${schema}."purchase"
        WHERE "status" = 1000
        ORDER BY "id"
      `);
      return result.rows.map((row) => ({
        ...row.data,
        number: row.number === null ? null : Number(row.number)
      }));
    },

    async findNotDistributed(orgid, buildResponse) {
      const schema = schemaFromOrgid(orgid);
      const result = await pool.query(`
        SELECT "id", "date"::text, "sortingdata"
        FROM ${schema}."purchase"
        WHERE "status" = 1001
        ORDER BY "id"
      `);
      return buildResponse(result.rows);
    },

    async updateSorting(orgid, sorting) {
      const schema = schemaFromOrgid(orgid);
      const client = await pool.connect();
      const rows = sorting.products.flatMap((product) =>
        product.sizes.map((size) => ({
          productid: product.productId,
          productdesc: product.name,
          sizeid: size.size,
          sizedesc: size.sizedesc,
          quantity: size.grossWeightKg
        }))
      );

      try {
        await client.query('BEGIN');
        await client.query(
          `SELECT pg_advisory_xact_lock(hashtext('sorting:' || $1 || ':' || $2))`,
          [orgid, String(sorting.purchaseNumber)]
        );
        await client.query(`
          CREATE TABLE IF NOT EXISTS ${schema}."sorting" (
            "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "created_at" timestamptz NOT NULL DEFAULT now(),
            "purchasedate" date,
            "purchasenumber" numeric,
            "number" numeric,
            "productid" bigint,
            "productdesc" text,
            "sizeid" bigint,
            "sizedesc" text,
            "quantity" double precision,
            "allocatedquantity" double precision,
            "allocationcomplete" boolean NOT NULL DEFAULT false
          )
        `);
        await client.query(`
          ALTER TABLE ${schema}."sorting"
          ADD COLUMN IF NOT EXISTS "allocationcomplete" boolean
          NOT NULL DEFAULT false
        `);
        const purchaseResult = await client.query(`
          WITH target AS (
            SELECT "id"
            FROM ${schema}."purchase"
            WHERE "date" = $1::date
              AND "number" = $2::numeric
            ORDER BY "id" DESC
            LIMIT 1
            FOR UPDATE
          )
          UPDATE ${schema}."purchase" AS purchase
          SET "status" = 1001
          FROM target
          WHERE purchase."id" = target."id"
          RETURNING purchase."id", purchase."date"::text, purchase."number",
                    purchase."status"
        `, [sorting.purchaseDate, sorting.purchaseNumber]);

        if (purchaseResult.rowCount === 0) {
          const error = new Error(
            'No purchase row exists for the supplied date and purchase number'
          );
          error.code = 'PURCHASE_NOT_FOUND';
          throw error;
        }

        const sortingResult = await client.query(`
          WITH sorting_number AS MATERIALIZED (
            SELECT floor(random() * 900000000000 + 100000000000)::numeric
                   AS "number"
          ), incoming AS (
            SELECT *
            FROM jsonb_to_recordset($3::jsonb) AS item(
              "productid" bigint,
              "productdesc" text,
              "sizeid" bigint,
              "sizedesc" text,
              "quantity" double precision
            )
          )
          INSERT INTO ${schema}."sorting" (
            "purchasedate", "purchasenumber", "number", "productid",
            "productdesc", "sizeid", "sizedesc", "quantity",
            "allocatedquantity", "allocationcomplete"
          )
          SELECT $1::date, $2::numeric, sorting_number."number",
                 incoming."productid", incoming."productdesc",
                 incoming."sizeid", incoming."sizedesc", incoming."quantity",
                 NULL, false
          FROM incoming
          CROSS JOIN sorting_number
          RETURNING "id", "created_at", "purchasedate"::text,
                    "purchasenumber", "number", "productid", "productdesc",
                    "sizeid", "sizedesc", "quantity", "allocatedquantity",
                    "allocationcomplete"
        `, [
          sorting.purchaseDate,
          sorting.purchaseNumber,
          JSON.stringify(rows)
        ]);
        await client.query('COMMIT');

        return {
          ...purchaseResult.rows[0],
          sortingdata: sorting,
          sortingNumber: sortingResult.rows[0].number,
          insertedCount: sortingResult.rowCount,
          sortingRows: sortingResult.rows
        };
      } catch (error) {
        await client.query('ROLLBACK').catch(() => {});
        throw error;
      } finally {
        client.release();
      }
    },

    async create(orgid, purchase) {
      const schema = schemaFromOrgid(orgid);
      const client = await pool.connect();

      try {
        await client.query('BEGIN');
        await client.query(
          `SELECT pg_advisory_xact_lock(hashtext('purchase:' || $1))`,
          [orgid]
        );
        await client.query(`
          CREATE TABLE IF NOT EXISTS ${schema}."purchase" (
            "id" bigint PRIMARY KEY,
            "created_at" timestamptz NOT NULL DEFAULT now(),
            "date" date,
            "data" jsonb,
            "status" bigint,
            "sortingdata" jsonb,
            "number" numeric
          )
        `);
        await client.query(`
          ALTER TABLE ${schema}."purchase"
          ADD COLUMN IF NOT EXISTS "number" numeric
        `);
        const result = await client.query(`
          WITH next_id AS (
            SELECT COALESCE(MAX("id"), 0) + 1 AS "id"
            FROM ${schema}."purchase"
          )
          INSERT INTO ${schema}."purchase"
            ("id", "date", "data", "status", "number")
          SELECT "id", $1::date, $2::jsonb, 1000,
                 floor(extract(epoch FROM clock_timestamp()) * 1000)::numeric
          FROM next_id
          RETURNING "id", "date"::text, "data", "status", "number",
                    "created_at"
        `, [
          purchase.purchaseDate,
          JSON.stringify(purchase)
        ]);
        await client.query('COMMIT');
        const row = result.rows[0];
        return {
          id: row.id,
          purchase_date: row.date,
          total_cost: row.data.totalCost,
          currency: row.data.currency,
          products: row.data.products,
          notes: row.data.notes,
          status: Number(row.status),
          number: row.number,
          created_at: row.created_at
        };
      } catch (error) {
        await client.query('ROLLBACK').catch(() => {});
        throw error;
      } finally {
        client.release();
      }
    }
  };
}

module.exports = { createPurchaseRepository };
